// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type Options as Options2, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { CreateUserAuthPostData, CreateUserAuthPostErrors, CreateUserAuthPostResponses, CreateUserProfileUserProfilePostData, CreateUserProfileUserProfilePostErrors, CreateUserProfileUserProfilePostResponses, DeleteUserProfileUserProfileDeleteData, DeleteUserProfileUserProfileDeleteErrors, DeleteUserProfileUserProfileDeleteResponses, GetUserProfileUserProfileGetData, GetUserProfileUserProfileGetResponses, LoginForAccessTokenAuthTokenPostData, LoginForAccessTokenAuthTokenPostErrors, LoginForAccessTokenAuthTokenPostResponses, ReadRootGetData, ReadRootGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Read Root
 */
export const readRootGet = <ThrowOnError extends boolean = false>(options?: Options<ReadRootGetData, ThrowOnError>) => (options?.client ?? client).get<ReadRootGetResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Create User
 */
export const createUserAuthPost = <ThrowOnError extends boolean = false>(options: Options<CreateUserAuthPostData, ThrowOnError>) => (options.client ?? client).post<CreateUserAuthPostResponses, CreateUserAuthPostErrors, ThrowOnError>({
    url: '/auth/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Login For Access Token
 */
export const loginForAccessTokenAuthTokenPost = <ThrowOnError extends boolean = false>(options: Options<LoginForAccessTokenAuthTokenPostData, ThrowOnError>) => (options.client ?? client).post<LoginForAccessTokenAuthTokenPostResponses, LoginForAccessTokenAuthTokenPostErrors, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    url: '/auth/token',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options.headers
    }
});

/**
 * Delete Userprofile
 */
export const deleteUserProfileUserProfileDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteUserProfileUserProfileDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteUserProfileUserProfileDeleteResponses, DeleteUserProfileUserProfileDeleteErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/UserProfile/',
    ...options
});

/**
 * Get User Profile
 */
export const getUserProfileUserProfileGet = <ThrowOnError extends boolean = false>(options?: Options<GetUserProfileUserProfileGetData, ThrowOnError>) => (options?.client ?? client).get<GetUserProfileUserProfileGetResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/UserProfile/',
    ...options
});

/**
 * Create Userprofile
 */
export const createUserProfileUserProfilePost = <ThrowOnError extends boolean = false>(options: Options<CreateUserProfileUserProfilePostData, ThrowOnError>) => (options.client ?? client).post<CreateUserProfileUserProfilePostResponses, CreateUserProfileUserProfilePostErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/UserProfile/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
