// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://schema.json` | (string & {});
};

/**
 * Body_login_for_access_token_auth_token_post
 */
export type BodyLoginForAccessTokenAuthTokenPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * UserCreateResponse
 */
export type UserCreateResponse = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserProfileCreate
 */
export type UserProfileCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateUserAuthPostData = {
    body: UserCreateResponse;
    path?: never;
    query?: never;
    url: '/auth/';
};

export type CreateUserAuthPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserAuthPostError = CreateUserAuthPostErrors[keyof CreateUserAuthPostErrors];

export type CreateUserAuthPostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type LoginForAccessTokenAuthTokenPostData = {
    body: BodyLoginForAccessTokenAuthTokenPost;
    path?: never;
    query?: never;
    url: '/auth/token';
};

export type LoginForAccessTokenAuthTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginForAccessTokenAuthTokenPostError = LoginForAccessTokenAuthTokenPostErrors[keyof LoginForAccessTokenAuthTokenPostErrors];

export type LoginForAccessTokenAuthTokenPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginForAccessTokenAuthTokenPostResponse = LoginForAccessTokenAuthTokenPostResponses[keyof LoginForAccessTokenAuthTokenPostResponses];

export type DeleteUserProfileUserProfileDeleteData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Userprofile Id
         */
        UserProfile_id: number;
    };
    url: '/UserProfile/';
};

export type DeleteUserProfileUserProfileDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserProfileUserProfileDeleteError = DeleteUserProfileUserProfileDeleteErrors[keyof DeleteUserProfileUserProfileDeleteErrors];

export type DeleteUserProfileUserProfileDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetUserProfileUserProfileGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Userprofile Id
         */
        UserProfile_id: number;
    };
    url: '/UserProfile/';
};

export type GetUserProfileUserProfileGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserProfileUserProfileGetError = GetUserProfileUserProfileGetErrors[keyof GetUserProfileUserProfileGetErrors];

export type GetUserProfileUserProfileGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateUserProfileUserProfilePostData = {
    body: UserProfileCreate;
    path?: never;
    query?: never;
    url: '/UserProfile/';
};

export type CreateUserProfileUserProfilePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserProfileUserProfilePostError = CreateUserProfileUserProfilePostErrors[keyof CreateUserProfileUserProfilePostErrors];

export type CreateUserProfileUserProfilePostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type GetUserProfileUserProfileUserProfileGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/UserProfile/UserProfile';
};

export type GetUserProfileUserProfileUserProfileGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
